In [10]:
import numpy as np

In [11]:
a = np.array([3,4,5,6,76])

In [12]:
type(a)

numpy.ndarray

In [13]:
a1 = np.array([[3,4,5] , [2,3,4]])

In [14]:
a1

array([[3, 4, 5],
       [2, 3, 4]])

In [15]:
a1.shape

(2, 3)

In [16]:
a1.ndim

2

In [17]:
a1.size

6

In [18]:
np.random.randint(1,10,(3,3))

array([[3, 9, 4],
       [1, 2, 5],
       [4, 3, 1]])

In [19]:
np.random.randint(1,10,(4,3))

array([[7, 3, 5],
       [1, 9, 8],
       [7, 2, 4],
       [8, 6, 2]])

In [20]:
np.random.randint(1,10,(2,4,3))

array([[[3, 6, 6],
        [9, 5, 5],
        [5, 7, 4],
        [4, 1, 5]],

       [[3, 2, 8],
        [7, 1, 6],
        [6, 7, 7],
        [3, 8, 4]]])

In [21]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [22]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
a1 = np.array([3,4,5,6,7,7])
a2 = np.array([5,6,4,3,2,3])

In [24]:
a1+a2

array([ 8, 10,  9,  9,  9, 10])

In [25]:
a1*a2

array([15, 24, 20, 18, 14, 21])

In [26]:
a1/a2

array([0.6       , 0.66666667, 1.25      , 2.        , 3.5       ,
       2.33333333])

In [27]:
a3 = np.array([[3,4,5] , [1,2,3]])
a4 = np.array([[2,3,4] , [1,2,3]])

In [28]:
a3

array([[3, 4, 5],
       [1, 2, 3]])

In [29]:
a4

array([[2, 3, 4],
       [1, 2, 3]])

In [30]:
a3+a4

array([[5, 7, 9],
       [2, 4, 6]])

In [31]:
a3*a4

array([[ 6, 12, 20],
       [ 1,  4,  9]])

In [32]:
a3

array([[3, 4, 5],
       [1, 2, 3]])

In [33]:
a4

array([[2, 3, 4],
       [1, 2, 3]])

In [34]:
a1 = np.array([[2,3],[1,2]])
a2 = np.array([[1,2] ,[2,3]])

In [35]:
a1

array([[2, 3],
       [1, 2]])

In [36]:
a2

array([[1, 2],
       [2, 3]])

In [37]:
a1*a2

array([[2, 6],
       [2, 6]])

In [38]:
a1@a2

array([[ 8, 13],
       [ 5,  8]])

In [39]:
np.dot(a1,a2)


array([[ 8, 13],
       [ 5,  8]])

In [40]:
additioanal_data  = np.random.randint(2,4 , (847, 1810, 3))

In [41]:
additioanal_data.shape

(847, 1810, 3)

In [42]:
a.mean()

np.float64(18.8)

In [43]:
a.std()

np.float64(28.6174771774173)

In [44]:
a.min()

np.int64(3)

In [45]:
a.max()

np.int64(76)

In [46]:
a.var()

np.float64(818.96)

In [47]:
np.log10(a)

array([0.47712125, 0.60205999, 0.69897   , 0.77815125, 1.88081359])

In [48]:
np.exp(a)

array([2.00855369e+01, 5.45981500e+01, 1.48413159e+02, 4.03428793e+02,
       1.01480039e+33])

In [49]:
a1

array([[2, 3],
       [1, 2]])

In [50]:
np.linalg.inv(a1)

array([[ 2., -3.],
       [-1.,  2.]])